# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Messages' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Messages
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    
    
  target 'MessagesTests' do
    inherit! :search_paths
    # Pods for testing
     pod 'Firebase'
     pod 'Firebase/Analytics'
     pod 'Firebase/Core'
     pod 'OHHTTPStubs'
     pod 'OHHTTPStubs/Swift' # Adds the Swiftier API wrapper too
  end

  target 'MessagesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
